Failing UI tests for path_buf_push
Copied over tests from `join_absolute_paths` and adapted them to this API. The original tests are:


```
    let path = Path::new("/bin");
    path.join("/sh");
    //~^ join_absolute_paths

    let path = PathBuf::from("/bin");
    path.join("/sh");
    //~^ join_absolute_paths

    let path = PathBuf::from("/bin");
    path.join(r#"/sh"#);
    //~^ join_absolute_paths

    let path = Path::new("C:\\Users");
    path.join("\\user");
    //~^ join_absolute_paths

    let path = PathBuf::from("C:\\Users");
    path.join("\\user");
    //~^ join_absolute_paths

    let path = PathBuf::from("C:\\Users");
    path.join(r#"\user"#);
    //~^ join_absolute_paths

    let path: &[&str] = &["/bin"];
    path.join("/sh");

    let path = Path::new("/bin");
    path.join("sh");
```

This fails because this lint does not fire on the paths that use a Windows-style slash (`\`).

```
error: diagnostic code `clippy::path_buf_push_overwrite` not found on line 11
  --> tests/ui/path_buf_push_overwrite.rs:12:10
   |
12 |     //~^ path_buf_push_overwrite
   |          ^^^^^^^^^^^^^^^^^^^^^^^ expected because of this pattern
   |

error: diagnostic code `clippy::path_buf_push_overwrite` not found on line 15
  --> tests/ui/path_buf_push_overwrite.rs:16:10
   |
16 |     //~^ path_buf_push_overwrite
   |          ^^^^^^^^^^^^^^^^^^^^^^^ expected because of this pattern
```